[project]
name = "carevault-api"
version = "0.1.0"
description = "CareVault API - FastAPI backend for clinical workflow management"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.5",
    "uvicorn[standard]==0.32.1",
    "sqlalchemy==2.0.35",
    "alembic==1.14.0",
    "python-jose[cryptography]==3.3.0",
    "passlib[bcrypt]==1.7.4",
    "python-multipart==0.0.12",
    "pydantic==2.10.2",
    "pydantic-settings==2.6.1",
    "httpx==0.28.0",
    "python-dotenv==1.0.1",
    "qrcode[pil]==8.0",
    "reportlab==4.4.1",
    "openai==1.58.1",
    "aiofiles==24.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "pytest-asyncio==0.25.0",
    "pytest-cov==6.0.0",
    "black==24.10.0",
    "ruff==0.8.3",
    "mypy==1.13.0",
    "pre-commit==4.0.1",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "I", "N", "W"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]